In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('c:/000625.csv',encoding='utf8')
df

,Unnamed: 0,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,0,000625.SZ,20210611,23.20,23.99,22.23,23.29,23.29,0.00,0.0000,2018951.06,4693894.018
1,1,000625.SZ,20210610,22.23,23.67,22.12,23.29,22.53,0.76,3.3733,1735938.09,4017384.297
2,2,000625.SZ,20210609,22.50,22.83,22.10,22.53,22.51,0.02,0.0888,904285.45,2041048.271
3,3,000625.SZ,20210608,22.68,23.45,22.06,22.51,22.80,-0.29,-1.2719,1330301.24,3022493.016
4,4,000625.SZ,20210607,23.58,23.75,22.38,22.80,23.58,-0.78,-3.3079,1612557.30,3691173.993
...,...,...,...,...,...,...,...,...,...,...,...,...
101,101,000625.SZ,20210108,22.90,23.59,21.80,23.43,22.69,0.74,3.2613,2363164.71,5384089.157
102,102,000625.SZ,20210107,21.34,23.00,20.60,22.69,21.13,1.56,7.3829,2594173.97,5685951.180
103,103,000625.SZ,20210106,21.30,21.73,20.60,21.13,21.03,0.10,0.4755,1250232.45,2639324.343
104,104,000625.SZ,20210105,21.89,22.11,20.95,21.03,21.75,-0.72,-3.3103,1482878.57,3151772.050
105,105,000625.SZ,20210104,21.20,22.30,21.01,21.75,21.88,-0.13,-0.5941,1359361.28,2951944.056

In [23]:
df.pivot_table(index="trade_date",values=["open","close","vol"])

            close   open         vol
trade_date
20210104    21.75  21.20  1359361.28
20210105    21.03  21.89  1482878.57
20210106    21.13  21.30  1250232.45
20210107    22.69  21.34  2594173.97
20210108    23.43  22.90  2363164.71
...           ...    ...         ...
20210607    22.80  23.58  1612557.30
20210608    22.51  22.68  1330301.24
20210609    22.53  22.50   904285.45
20210610    23.29  22.23  1735938.09
20210611    23.29  23.20  2018951.06

[106 rows x 3 columns]

In [25]:
df.pivot_table(index="trade_date",values=["open","close","vol"],aggfunc=[df[df['vol']>df['vol'].mean()]])

TypeError: 'numpy.ndarray' object is not callable

In [10]:
df[df['vol']>df['vol'].mean()]

,Unnamed: 0,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,0,000625.SZ,20210611,23.20,23.99,22.23,23.29,23.29,0.00,0.0000,2018951.06,4.693894e+06
1,1,000625.SZ,20210610,22.23,23.67,22.12,23.29,22.53,0.76,3.3733,1735938.09,4.017384e+06
4,4,000625.SZ,20210607,23.58,23.75,22.38,22.80,23.58,-0.78,-3.3079,1612557.30,3.691174e+06
5,5,000625.SZ,20210604,23.21,24.25,22.88,23.58,23.40,0.18,0.7692,1579830.98,3.741706e+06
6,6,000625.SZ,20210603,23.10,23.90,22.45,23.40,22.96,0.44,1.9164,1587474.40,3.701044e+06
7,7,000625.SZ,20210602,23.50,23.93,22.77,22.96,23.79,-0.83,-3.4889,1635463.60,3.819865e+06
8,8,000625.SZ,20210601,23.40,24.69,23.20,23.79,23.75,0.04,0.1684,2149840.42,5.123708e+06
9,9,000625.SZ,20210531,22.70,24.10,22.20,23.75,23.04,0.71,3.0816,2337159.69,5.464532e+06
10,10,000625.SZ,20210528,21.72,23.70,21.30,23.04,21.76,1.28,5.8824,2927468.09,6.631635e+06
11,11,000625.SZ,20210527,22.50,22.60,21.56,21.76,22.15,-0.39,-1.7607,1668592.82,3.652341e+06
12,12,000625.SZ,20210526,21.51,22.52,21.51,22.15,21.50,0.65,3.0233,2336065.81,5.148668e+06
13,13,000625.SZ,20210525,22.10,22.11,21.03,21.50,22.50,-1.00,-4.4444,2794628.74,6.018710e+06
14,14,000625.SZ,20210524,23.55,24.22,22.50,22.50,25.00,-2.50,-10.0000,3620095.68,8.416216e+06
15,15,000625.SZ,20210521,22.40,25.30,22.11,25.00,23.05,1.95,8.4599,3901036.70,9.206360e+06
16,16,000625.SZ,20210520,24.74,25.30,23.01,23.05,24.60,-1.55,-6.3008,3113038.79,7.614514e+06
17,17,000625.SZ,20210519,23.00,25.50,22.41,24.60,23.47,1.13,4.8147,2891394.07,6.886303e+06
18,18,000625.SZ,20210518,23.01,23.67,22.64,23.47,23.77,-0.30,-1.2621,2531684.27,5.836755e+06
19,19,000625.SZ,20210517,23.01,24.15,22.52,23.77,23.01,0.76,3.3029,3782037.28,8.864662e+06
20,20,000625.SZ,20210514,21.70,23.01,21.00,23.01,20.92,2.09,9.9904,3296491.68,7.309498e+06
21,21,000625.SZ,20210513,22.00,22.88,20.87,20.92,21.45,-0.53,-2.4709,4626727.95,1.016752e+07
22,22,000625.SZ,20210512,19.50,21.45,19.28,21.45,19.50,1.95,10.0000,1943770.00,4.051407e+06
23,23,000625.SZ,20210511,18.89,20.22,18.38,19.50,18.38,1.12,6.0936,4156299.64,8.047771e+06
24,24,000625.SZ,20210510,16.42,18.38,16.25,18.38,16.71,1.67,9.9940,2622325.75,4.650501e+06
26,26,000625.SZ,20210506,16.18,17.49,16.08,16.98,16.37,0.61,3.7263,1937235.69,3.265508e+06
29,29,000625.SZ,20210428,16.00,16.88,15.94,16.66,16.19,0.47,2.9030,1756865.20,2.885520e+06
31,31,000625.SZ,20210426,16.15,16.95,15.86,16.84,16.12,0.72,4.4665,2333525.13,3.828788e+06
33,33,000625.SZ,20210422,16.78,17.30,16.67,16.81,16.78,0.03,0.1788,1493401.42,2.533655e+06
34,34,000625.SZ,20210421,17.29,17.39,16.60,16.78,18.01,-1.23,-6.8295,2345044.71,3.974148e+06
35,35,000625.SZ,20210420,18.49,19.13,17.61,18.01,17.39,0.62,3.5653,3989697.05,7.322127e+06
36,36,000625.SZ,20210419,17.30,17.39,16.75,17.39,15.81,1.58,9.9937,1504261.44,2.586246e+06
37,37,000625.SZ,20210416,14.57,15.81,14.57,15.81,14.37,1.44,10.0209,1853285.27,2.862900e+06
71,71,000625.SZ,20210226,16.88,18.89,16.60,18.15,17.25,0.90,5.2174,1633424.39,2.910598e+06
81,81,000625.SZ,20210205,19.67,19.80,17.97,18.04,19.97,-1.93,-9.6645,1626559.66,3.040619e+06
83,83,000625.SZ,20210203,20.26,20.46,19.41,19.53,19.46,0.07,0.3597,2125345.45,4.235251e+06
91,91,000625.SZ,20210122,19.34,20.35,19.15,20.14,19.45,0.69,3.5476,1519587.27,3.005683e+06
97,97,000625.SZ,20210114,21.30,21.30,19.74,19.92,21.69,-1.77,-8.1604,1634892.85,3.339555e+06
99,99,000625.SZ,20210112,22.60,22.77,21.50,22.24,23.16,-0.92,-3.9724,1638048.25,3.620061e+06
100,100,000625.SZ,20210111,23.43,24.70,22.90,23.16,23.43,-0.27,-1.1524,2187771.96,5.223740e+06
101,101,000625.SZ,20210108,22.90,23.59,21.80,23.43,22.69,0.74,3.2613,2363164.71,5.384089e+06
102,102,000625.SZ,20210107,21.34,23.00,20.60,22.69,21.13,1.56,7.3829,2594173.97,5.685951e+06
104,104,000625.SZ,20210105,21.89,22.11,20.95,21.03,21.75,-0.72,-3.3103,1482878.57,3.151772e+06